#+SETUPFILE: setup.inc
#+TITLE: Emacs Chat: Conversations about an awesome text editor
#+DATE: <2014-04-25 Fri>

* Introduction

The Emacs community has a lot of amazing people, although we rarely get to meet face to face. It’s great to get a sense of what people are like, so here are some casual chats with other Emacs geeks. =) Want to talk about Emacs? [[http://sachachua.com/contact][I’d love to hear from you!]]

Want to subscribe to the podcast? Feed: http://sachachua.com/blog/tag/emacs-chat/podcast

#+BEGIN_HTML
<iframe src="http://www.youtube-nocookie.com/embed/videoseries?list=PL4th0AZixyRF8o3fdx68HGUrYKF2Pfvrp" width="640" height="360" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
#+END_HTML

* Emacs chats

Getting to know people who use Emacs

- [[file:chat-avdi-grimm.org][Avdi Grimm (Org-mode, Ruby, etc.)]]
- [[file:chat-bastien-guerry.org][Bastien Guerry]]
- [[file:chat-bozhidar-batsov.org][Bozhidar Batsov]] - Prelude
- [[file:chat-carsten-dominik.org][Carsten Dominik]]
- [[file:chat-christopher-wellons.org][Christopher Wellons]] - foreign function interface, skewer, impatient-mode
- [[file:chat-harry-r-schwartz.org][Harry R. Schwartz]] - EmacsNYC, organizing your configuration, pair programming
- [[file:chat-iannis-zannos.org][Iannis Zannos -- Emacs and SuperCollider]]
- [[file:chat-janis-mancevics.org][Jānis Mancēvičs]]
- [[file:chat-john-wiegley.org][John Wiegley]]
- [[file:chat-magnar-sveen.org][Magnar Sveen (Emacs Rocks)]]
- [[file:chat-mickey-petersen.org][Mickey Petersen (Mastering Emacs)]]
- [[file:phil-hagelberg.org][Phil Hagelberg (technomancy)]] - Clojure, Leiningen, Syme (for pair programming), custom keyboards, etc.
- [[file:chat-sacha-chua.org][Sacha Chua]]
- [[file:chat-thomas-kjeldahl-nilsson.org][Thomas Kjeldahl Nilsson]]
- [[file:chat-tom-marble.org][Tom Marble]]
- [[file:chat-xah-lee.org][Xah Lee]]

You can find this site at http://emacslife.com/emacs-chats . Source: http://github.com/sachac/emacs-chats - patches and pull requests much appreciated.

Have a story to share about how you got started with Emacs and what you use it for? Please contact me at [[mailto:sacha@sachachua.com][sacha@sachachua.com]] . Newbies welcome!

Sacha
