#+SETUPFILE: setup.org
#+TITLE: Emacs Chat: Conversations about an awesome text editor
#+DATE: <2014-04-25 Fri>

* Introduction

The Emacs community has a lot of amazing people, although we rarely get to meet face to face. It’s great to get a sense of what people are like, so here are some casual chats with other Emacs geeks. =) Want to talk about Emacs? [[http://sachachua.com/contact][I’d love to hear from you!]]

Want to subscribe to the podcast? Feed: http://sachachua.com/blog/tag/emacs-chat/podcast

#+BEGIN_HTML
<iframe src="http://www.youtube-nocookie.com/embed/videoseries?list=PL4th0AZixyRF8o3fdx68HGUrYKF2Pfvrp" width="640" height="360" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
#+END_HTML

* Emacs chats

Getting to know people who use Emacs

-  [[file:chat-janis-mancevics.org][Emacs Chat: Jānis Mancēvičs]]
-  [[file:chat-marble.org][Emacs Chat: Tom Marble]]
-  Emacs Chat: Iannis Zannos -- Emacs and SuperCollider
-  Emacs Chat: Magnar Sveen (Emacs Rocks)
-  Emacs Chat: Sacha Chua (with Bastien Guerry)
-  Emacs Chat: Bastien Guerry
-  Emacs Chat: Carsten Dominik
-  Emacs chat: Thomas Kjeldahl Nilsson
-  Emacs Chat with Avdi Grimm (Org-mode, Ruby, etc.)
-  [[chat-john-wiegley.org][Transcript: Emacs chat with John Wiegley]]
